// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ-EZJ5aT3g1tBgaXNcBu-2vW6kLy6HOU',
    appId: '1:404727318981:web:6a69b731d2fbc8498423ac',
    messagingSenderId: '404727318981',
    projectId: 'ridecare-74ef9',
    authDomain: 'ridecare-74ef9.firebaseapp.com',
    storageBucket: 'ridecare-74ef9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2N9prdjo-iqydPuLunsY7GJxKuBYoOec',
    appId: '1:404727318981:android:fc03c4e03ecd54d38423ac',
    messagingSenderId: '404727318981',
    projectId: 'ridecare-74ef9',
    storageBucket: 'ridecare-74ef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk3ZKqToZJardPRqkV5JirqVBR-TviiKg',
    appId: '1:404727318981:ios:c6cd91768bb167f78423ac',
    messagingSenderId: '404727318981',
    projectId: 'ridecare-74ef9',
    storageBucket: 'ridecare-74ef9.firebasestorage.app',
    iosBundleId: 'com.example.ridecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk3ZKqToZJardPRqkV5JirqVBR-TviiKg',
    appId: '1:404727318981:ios:c6cd91768bb167f78423ac',
    messagingSenderId: '404727318981',
    projectId: 'ridecare-74ef9',
    storageBucket: 'ridecare-74ef9.firebasestorage.app',
    iosBundleId: 'com.example.ridecare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ-EZJ5aT3g1tBgaXNcBu-2vW6kLy6HOU',
    appId: '1:404727318981:web:73a83d464dcfbeee8423ac',
    messagingSenderId: '404727318981',
    projectId: 'ridecare-74ef9',
    authDomain: 'ridecare-74ef9.firebaseapp.com',
    storageBucket: 'ridecare-74ef9.firebasestorage.app',
  );
}
